# Week 01

Mini Challenge - 1 : 
Its your turn now!! store the word hello in my_string. print the my_string + name.

In [26]:
my_string = "hello"
print(my_string + ' "Nilesh"')

hello "Nilesh"


Mini Challenge - 2 : 
Its your turn now!!! given the numbers stored in variables a and b. Can you write a simple code to compute the mean of these two numbers and assign it to a variable mean.

In [7]:
a,b = 24,30
mean = (a + b)/2
print("mean: ",mean)

mean:  27.0


Mini Challenge - 3 :
Can you access the last element of a l which is a list and find the last element of that list.

In [9]:
l = [1,1,2,2,3,4,5,6,1,15]
last_element = l[-1]
print("lsat_element: ", last_element)

lat_element:  15


Mini Challenge - 4 : Can you compute the square of a number assigned to a variable a using the math module?

In [14]:
import math

num = 4
square = math.pow(num,2)
print("square: ",square)

square:  16.0


Mini Challenge - 5 : 
Can you create a list of 10 numbers iterate through the list and print the square of each number ?

In [21]:
numbers = list(range(11))
number_square = [(x**2) for x in numbers]
print("numbers_square: ",number_square)

numbers_square:  [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# Week 02


Mini Challenge - 1 : 
Can you write a function square_root having default value of input a=9 and find the square-root of the same.

In [28]:
def square_root(a=9):
    return math.sqrt(a)

square_root()

3.0


Mini Challenge - 2 : 
Can you write a function function_tuple that takes in two numbers a and b and returns the sum as well as the product of these numbers


In [32]:
def function_tuple(a,b):
    add = a + b
    prod = a * b
    return add,prod

addition,product = function_tuple(5,6)
print("addition:",addition,"  product:",product)

addition: 11   product: 30


Mini Challenge - 3 : 
Can you write a lambda function to add two numbers a and b.

In [34]:
add = lambda a,b: a + b
add(3,7)

10

Mini Challenge - 4 :
Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1,45.6]]. Print the dtype and shape.

In [38]:
import numpy as np
list1 = [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1,45.6]]
matrix = np.array(list1)
print(matrix)
print("matrix shape",matrix.shape)
print("matrix type",type(matrix))

[[ 5.3 10.2 15.1]
 [20.4 25.3 30.9]
 [35.4 40.1 45.6]]
matrix shape (3, 3)
matrix type <class 'numpy.ndarray'>


In [ ]:
Mini Challenge - 5 :
Create an ndimensional array from randomly genrated numbers of shape (3,4), then rehape the array to (4,3)

In [56]:
ndarray = np.random.randint(50, size=(3, 4))
print(ndarray)
ndarray.resize(4,3)
print(ndarray)

[[21  6 23 13]
 [30 44 12  1]
 [45 38 33  6]]
[[21  6 23]
 [13 30 44]
 [12  1 45]
 [38 33  6]]
