# Week 01

Mini Challenge - 1 : 
Its your turn now!! store the word hello in my_string. print the my_string + name.

In [26]:
my_string = "hello"
print(my_string + ' "Nilesh"')

hello "Nilesh"


Mini Challenge - 2 : 
Its your turn now!!! given the numbers stored in variables a and b. Can you write a simple code to compute the mean of these two numbers and assign it to a variable mean.

In [7]:
a,b = 24,30
mean = (a + b)/2
print("mean: ",mean)

mean:  27.0


Mini Challenge - 3 :
Can you access the last element of a l which is a list and find the last element of that list.

In [9]:
l = [1,1,2,2,3,4,5,6,1,15]
last_element = l[-1]
print("lsat_element: ", last_element)

lat_element:  15


Mini Challenge - 4 : Can you compute the square of a number assigned to a variable a using the math module?

In [14]:
import math

num = 4
square = math.pow(num,2)
print("square: ",square)

square:  16.0


Mini Challenge - 5 : 
Can you create a list of 10 numbers iterate through the list and print the square of each number ?

In [21]:
numbers = list(range(11))
number_square = [(x**2) for x in numbers]
print("numbers_square: ",number_square)

numbers_square:  [0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


# Week 02


Mini Challenge - 1 : 
Can you write a function square_root having default value of input a=9 and find the square-root of the same.

In [28]:
def square_root(a=9):
    return math.sqrt(a)

square_root()

3.0


Mini Challenge - 2 : 
Can you write a function function_tuple that takes in two numbers a and b and returns the sum as well as the product of these numbers


In [32]:
def function_tuple(a,b):
    add = a + b
    prod = a * b
    return add,prod

addition,product = function_tuple(5,6)
print("addition:",addition,"  product:",product)

addition: 11   product: 30


Mini Challenge - 3 : 
Can you write a lambda function to add two numbers a and b.

In [34]:
add = lambda a,b: a + b
add(3,7)

10

In [38]:
import numpy as np
list1 = [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1,45.6]]
matrix = np.array(list1)
print(matrix)
print("matrix shape",matrix.shape)
print("matrix type",type(matrix))

[[ 5.3 10.2 15.1]
 [20.4 25.3 30.9]
 [35.4 40.1 45.6]]
matrix shape (3, 3)
matrix type <class 'numpy.ndarray'>


In [8]:
ndarray = np.random.randint(50, size=(3, 4))
print(ndarray)
ndarray.resize(4,3)
print(ndarray)

[[ 2 39 33 42]
 [ 0 33  3 21]
 [ 6 20 20 28]]
[[ 2 39 33]
 [42  0 33]
 [ 3 21  6]
 [20 20 28]]


# Week 03

In [54]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("arr:\n",arr)
i,j = np.where(arr==5)
print("position: ",i,j)



arr:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
position:  [1] [1]


In [55]:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11,12,13,14,15]])
print(arr[:2,:3])

[[1 2 3]
 [6 7 8]]


In [57]:
import pandas as pd
ser1 = pd.Series([1,2,3,4], index=['USA', 'Germany','USSR', 'Japan']) 
ser2 = pd.Series([1,2,5,4], index=['USA', 'Germany','Italy', 'Japan'])
print(ser1['USSR'])

3


# Week 04

In [67]:
weather_df = pd.read_csv("./data/weather_2012.csv")
print(weather_df.head())

             Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0  2012-01-01 00:00:00      -1.8                -3.9           86   
1  2012-01-01 01:00:00      -1.8                -3.7           87   
2  2012-01-01 02:00:00      -1.8                -3.4           89   
3  2012-01-01 03:00:00      -1.5                -3.2           88   
4  2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog  


In [69]:
weather_df['Wind Spd (km/h)'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [83]:
weather_df['Weather'].value_counts()['Clear']

1326

In [88]:
weather_df['Wind Spd (km/h)'].value_counts()[4]

474

In [90]:
weather_df[['Visibility (km)','Rel Hum (%)']].iloc[:5:2]

Visibility (km)  Rel Hum (%)
0              8.0           86
2              4.0           89
4              4.8           88